"""crear fact_poi_city y seed de categorias

Revision ID: 2afd742cbc8a
Revises: d8672731404b
Create Date: 2026-08-03 18:17:55.052079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2afd742cbc8a'
down_revision: Union[str, Sequence[str], None] = 'd8672731404b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_poi_city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Date(), nullable=False),
    sa.Column('poi_category_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['dim_city.id'], ),
    sa.ForeignKeyConstraint(['date_id'], ['dim_date.date'], ),
    sa.ForeignKeyConstraint(['poi_category_id'], ['dim_poi_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'date_id', 'poi_category_id', name='uq_fact_poi_city_city_date_category')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_poi_city')
    # ### end Alembic commands ###
