"""crear star schema

Revision ID: d3b712ba013f
Revises: 
Create Date: 2026-07-31 18:15:09.530020

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd3b712ba013f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dim_date',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('dim_poi_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('fact_daily_city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Date(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('hotels', sa.Integer(), nullable=True),
    sa.Column('restaurants', sa.Integer(), nullable=True),
    sa.Column('museums', sa.Integer(), nullable=True),
    sa.Column('parks', sa.Integer(), nullable=True),
    sa.Column('hospitals', sa.Integer(), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['dim_city.id'], ),
    sa.ForeignKeyConstraint(['date_id'], ['dim_date.date'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_tourism_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['dim_city.id'], ),
    sa.ForeignKeyConstraint(['date_id'], ['dim_date.date'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_tourism_score')
    op.drop_table('fact_daily_city')
    op.drop_table('dim_poi_category')
    op.drop_table('dim_date')
    op.drop_table('dim_city')
    # ### end Alembic commands ###
