"""unique city-date en fact_daily_city

Revision ID: d8672731404b
Revises: d3b712ba013f
Create Date: 2026-08-03 17:37:30.823621

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd8672731404b'
down_revision: str | Sequence[str] | None = 'd3b712ba013f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'uq_fact_daily_city_city_date', 'fact_daily_city', ['city_id', 'date_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_fact_daily_city_city_date', 'fact_daily_city', type_='unique')
    # ### end Alembic commands ###
